import Head from 'next/head'
import Link from 'next/link'
import AppLayout from '../components/AppLayout';
//import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div>
      
      <Head>
        <title>Dev Twitter | Home</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <AppLayout>
        <h1>
          <a href="https://nextjs.org">dev-twitter</a>
        </h1>
        <nav>
          <Link href="/timeline">
            <a>timeline</a>
          </Link>
        </nav>
      </AppLayout>

      <style jsx>{`
        h1 {
          text-align: center;
          font-size: 48px;
        }

        nav {
          font-size: 24px;
          text-align: center;
        }

        .another-title {
          color: #333;
          font-size: 24px;
        }

        a {
          color: #09f;
          text-decoration: none;
        }
      `}</style>
    </div>
  );
}
