import { useEffect } from 'react';
import Head from 'next/head'
import Button from 'components/Button';
import GitHub from 'components/Icons/GitHub';
import { colors } from 'styles/theme';
import { loginWithGitHub } from 'firebase/client'
import { useRouter } from 'next/router';
import useUser, { USER_STATES } from 'hooks/useUser';

export default function Home() {
  const user = useUser()
  const router = useRouter()

  useEffect(() => {
    user && router.replace('/home')
  }, [user])

  const handleClick = () => {
    loginWithGitHub().catch(err => {
      console.log(err);
    })
  }

  return (
    <div>
      
      <Head>
        <title>Dev Twitter | Home</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

        <section>
          <h1>
            dev-twitter
          </h1>
          <h2>Talk about development with developers</h2>
          <div>
            {
              user === USER_STATES.NOT_LOGGED && <Button onClick={handleClick}>
                <GitHub fill={`${colors.white}`} width={24} height={24} />
                Login with GitHub
              </Button>
            }
            {
              user === USER_STATES.NOT_KNOWN && <span>Loading...</span>
            }
          </div>
        </section>

      <style jsx>{`

        section {
          display: grid;
          height: 100%;
          place-content: center;
          place-items: center;
        }

        img {
          width: 120px;
        }

        div {
          margin-top: 8px;
        }

        h1 {
          color: ${colors.primary};
          font-size: 24px;
          margin-bottom: 10px;
        }

        h2 {
          color: ${colors.secondary};
          font-size: 16px;
          margin: 0;
        }

      `}</style>
    </div>
  );
}

/**
 * && user.avatar && <div>
                <Avatar 
                  src={user.avatar} 
                  alt={user.username} 
                  text={user.username}
                  withText
                />
              </div>
 */