import { useEffect, useState } from 'react';
import Head from 'next/head'
import AppLayout from '../components/AppLayout';
import Button from '../components/Button';
import GitHub from '../components/Icons/GitHub';
import { colors } from '../styles/theme';
import {loginWithGitHub, onAuthStateChanged} from '../firebase/client'

export default function Home() {
  const [user, setUser] = useState(undefined)

  useEffect(() => {
    onAuthStateChanged(setUser)
  }, [])

  const handleClick = () => {
    loginWithGitHub().then(setUser).catch(err => {
      console.log(err);
    })
  }

  return (
    <div>
      
      <Head>
        <title>Dev Twitter | Home</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <AppLayout>
        <section>
          <h1>
            dev-twitter
          </h1>
          <h2>Talk about development with developers</h2>
          <div>
            {
              user === undefined && <Button onClick={handleClick}>
                <GitHub fill={`${colors.white}`} width={24} height={24} />
                Login with GitHub
              </Button>
            }
            {
              user && user.avatar && <div>
                <img src={user.avatar} alt={user.avatar} />
                <strong>{user.username}</strong>
              </div>
            }
            
          </div>
        </section>
      </AppLayout>

      <style jsx>{`

        section {
          display: grid;
          height: 100%;
          place-content: center;
          place-items: center;
        }

        img {
          width: 120px;
        }

        div {
          margin-top: 8px;
        }

        h1 {
          color: ${colors.primary};
          font-size: 24px;
          margin-bottom: 10px;
        }

        h2 {
          color: ${colors.secondary};
          font-size: 16px;
          margin: 0;
        }

      `}</style>
    </div>
  );
}
